# AWS Production Deployment with ECS/Fargate
version: '3.8'

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/toneslyder-backend:${VERSION:-latest}
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/toneslyder-frontend:${VERSION:-latest}
    environment:
      VITE_API_URL: ${API_URL}
    ports:
      - "80:80"
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: "0.25"
